### ISSUE TITLE
Mangafox image keeps spinning

### ISSUE THREAD

**Issue by Keats** [Saishy/certainmangareader#2]
Hey, 
Using 2.0.0-beta2 images on mangafox don't load 90% of the time.
Sometimes a refresh might work but quite often it just does not load.
I'll have a look if i can spot the issue when I have time

**Comment by Saishy** [comment]
Sorry for your issue, it has been fixed already but the next update is taking a while because it's really huge :2

**Comment by Keats** [comment]
Cool, waiting for it then !
Another thing unrelated but it would be nice to have a button to go the next unread chapter

**Comment by Saishy** [comment]
A new update for the beta has been pushed. Thanks for waiting!

**Comment by Keats** [comment]
Thanks, I still have the issue when i select a chapter from the dropdown but after a refresh it works
